# Generated by Django 4.2.18 on 2025-01-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_num', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('vendor', models.CharField(max_length=50)),
                ('vendor_part_number', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('moq', models.IntegerField()),
                ('package', models.CharField(max_length=50)),
                ('production_time', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('duty_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tariff_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imprint_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(max_length=50)),
                ('sales_rep', models.CharField(max_length=50)),
                ('carton_qty', models.IntegerField()),
                ('carton_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carton_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carton_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carton_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imprint_location', models.CharField(max_length=50)),
                ('imprint_method', models.CharField(max_length=50)),
                ('imprint_dimension', models.CharField(max_length=50)),
                ('quantity1', models.IntegerField()),
                ('quantity2', models.IntegerField()),
                ('quantity3', models.IntegerField()),
                ('quantity4', models.IntegerField()),
                ('quantity5', models.IntegerField()),
                ('qty1_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty2_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty3_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty4_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty5_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty1_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty2_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty3_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty4_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty5_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
