# Generated by Django 4.2.18 on 2025-01-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_air_freight_quote_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='date_created',
        ),
    ]
