# Generated by Django 4.2.18 on 2025-01-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_date_created_alter_quote_air_freight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='image_url',
            field=models.CharField(default='https://via.placeholder.com/150', max_length=2083),
        ),
    ]
