# Generated by Django 4.2.18 on 2025-02-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
