# Generated by Django 4.2.18 on 2025-04-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_alter_quote_qty1_cost_alter_quote_qty1_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='qty1_price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='qty2_price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='qty3_price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='qty4_price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='qty5_price',
        ),
        migrations.AddField(
            model_name='quote',
            name='qty1_price_air',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='qty1_price_ocean',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='qty2_price_air',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='qty2_price_ocean',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='qty3_price_air',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='qty3_price_ocean',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='qty4_price_air',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='qty4_price_ocean',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='qty5_price_air',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='qty5_price_ocean',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
