# Generated by Django 4.2.18 on 2025-04-20 13:11

from django.db import migrations

def migrate_prices(apps, schema_editor):
    Quote = apps.get_model('quotes', 'Quote')
    for i in range(1, 6):
        for quote in Quote.objects.all():
            price = getattr(quote, f'qty{i}_price', None)
            if price is not None:
                setattr(quote, f'qty{i}_price_air', price)
                quote.save()

class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_remove_quote_qty1_price_remove_quote_qty2_price_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_prices),
    ]
