# Generated by Django 4.2.18 on 2025-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_migrate_legacy_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='air_transit_time',
            field=models.CharField(default='7-10 days', max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='ocean_transit_time',
            field=models.CharField(default='~6 weeks', max_length=50),
        ),
    ]
