# Generated by Django 4.2.18 on 2025-04-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_quote_air_transit_time_quote_ocean_transit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Added', 'Added'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
    ]
