# Generated by Django 4.2.18 on 2025-04-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_alter_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
