# Generated by Django 4.2.18 on 2025-04-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_quote_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='reciprocal_tariffs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
