# Generated by Django 4.2.18 on 2025-04-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_quote_reciprocal_tariffs_alter_quote_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='reciprocal_tariffs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
