# Generated by Django 4.2.18 on 2025-01-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('moq', models.IntegerField()),
                ('package', models.CharField(max_length=50)),
                ('production_time', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('duty_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tariff_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carton_qty', models.IntegerField()),
                ('carton_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carton_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carton_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carton_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imprint_location', models.CharField(max_length=50)),
                ('imprint_method', models.CharField(max_length=50)),
                ('imprint_dimension', models.CharField(max_length=50)),
                ('price_list', models.BooleanField(default=False)),
                ('product_list', models.BooleanField(default=False)),
                ('hts_list', models.BooleanField(default=False)),
                ('npds_done', models.BooleanField(default=False)),
                ('qb_added', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
