# Generated by Django 4.2.18 on 2025-01-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_launch',
            field=models.CharField(default='TBA', max_length=50),
            preserve_default=False,
        ),
    ]
