# Generated by Django 4.2.18 on 2025-01-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(default='vendor', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_sku',
            field=models.CharField(default='vendor sku', max_length=50),
            preserve_default=False,
        ),
    ]
