# Generated by Django 4.2.18 on 2025-01-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_vendor_product_vendor_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
