# Generated by Django 4.2.18 on 2025-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(default='white', max_length=150),
            preserve_default=False,
        ),
    ]
